FROM ubuntu:18.10
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
      git-core \
      nasm \
      build-essential \
      meson \
      ninja-build \
      libglib2.0-dev \
      cmake \
      libx11-dev \
      libnss3 \
      libnspr4 \
      libx11-xcb-dev \
      libxcb1 \
      libxcomposite-dev \
      libxcursor-dev \
      libxdamage-dev \
      libxfixes-dev \
      libxi-dev \
      libxrender-dev \
      libxtst-dev \
      fontconfig \
      libxrandr-dev \
      libxss-dev \
      libasound2 \
      libcairo2 \
      libpango1.0-0 \
      libatk1.0-0 \
      pulseaudio-utils \
      libarchive-dev \
      liborc-dev \
      flex \
      bison \
      libpulse-dev \
      libsoup2.4-dev \
      unzip \
      libatk-adaptor \
      at-spi \
      sudo \
      libjson-glib-dev \
      python3-pip && \
      apt-get clean && \
      rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp*

RUN   python3 -m pip install setuptools && \
      python3 -m pip install meson --upgrade

# We compile libx264 ourselves in order to have libx264.so
# provide support for both 8-nit and 10-bit
RUN git clone https://git.videolan.org/git/x264.git && \
    cd x264 && \
    ./configure --prefix=/usr --bit-depth=all --chroma-format=all --enable-pic --enable-shared && \
    make -j && \
    make install && \
    cd .. && \
    rm -rf x264

# We compile ffmpeg ourselves as we depend on a patch that should
# soon land in master for mpeg-2 CC injection support
RUN git clone https://github.com/FFmpeg/FFmpeg.git && \
    cd FFmpeg && \
    ./configure \
    --disable-debug \
    --disable-doc \
    --disable-ffplay \
    --enable-shared \
    --enable-decoder=h264 \
    --enable-encoder=ac3 \
    --enable-encoder=eac3 \
    --enable-encoder=mp2 \
    --enable-encoder=mpeg2video \
    --enable-decoder=eac3 \
    --prefix=/usr && \
    make -j && \
    make install && \
    cd .. && \
    rm -rf FFmpeg

# We will have some patches in gstreamer's master repositories
# that we will depend on, so build these ourselves
RUN git clone https://github.com/GStreamer/gst-build.git && \
    cd gst-build && \
    meson build --prefix=/usr && \
    ninja -C build && \
    ninja -C build install && \
    cd .. && \
    rm -rf gst-build